# Generated by Django 3.1.7 on 2021-03-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roles', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096)),
                ('cost_assign', models.IntegerField(default=0)),
                ('cost_close', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True)),
                ('plus', models.IntegerField(default=0)),
                ('minus', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=4096)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.employee')),
            ],
        ),
    ]
