# Generated by Django 3.1.7 on 2021-03-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
