# Generated by Django 3.1.7 on 2021-03-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096)),
                ('status', models.IntegerField(default=1)),
                ('open_date', models.DateTimeField(auto_now=True)),
                ('close_date', models.DateTimeField(verbose_name='date closed')),
                ('cost', models.IntegerField(default=0)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjira.employee')),
            ],
        ),
    ]
