# Generated by Django 3.1.7 on 2021-03-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'OPEN'), (2, 'CLOSED')], default=1),
        ),
    ]
