# Generated by Django 3.1.7 on 2021-03-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjira', '0005_auto_20210314_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.JSONField(default=list),
        ),
    ]
